server:
  port: 8781

#server name
spring:
  redis:
    database: 0
    host: 172.18.148.27
    port: 9736
    timeout: 2000
  # zipkin
  zipkin:
    base-url: http://localhost:9411/
  # sampling percentage,0.1-1,usually use the default configuration
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 172.18.148.27
    port: 5672
    username: guest
    password: guest

#custom load balance,default RoundRobinRule,more(to see IRule)
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

#hystrix defualt 1s
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 2 000
        loggerLevel: basic

# change the defualt timeoutInMilliseconds
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

# Expose "hystrix.stream" monitoring information
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,bus-refresh,bus-env
