# server name
spring:
  # Specify which registry to read from
  cloud:
    config:
      discovery:
        service-id: CONFIG-SERVER
        enabled: true
      # env
      profile: dev
      # branch
      label: master

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
      web:
        exposure:
          include: bus-refresh,bus-env

env: dev
branch: master
