server:
  port: 8772
# server name
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
      web:
        exposure:
          include: bus-refresh,bus-env

env: dev
branch: master
